import Head from "next/head";
import { SidebarLayout } from "~/components/layout";
import { TicketList } from "~/components/ui";
import { api } from "~/utils/api";
import { type NextPageWithLayout } from "../_app";

const Home: NextPageWithLayout = () => {
  const { isLoading, data } = api.orders.getAllByCurrentUser.useQuery();
  console.log(data);
  return (
    <>
      <Head>
        <title>MovieMania 🎬 - My Tickets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <TicketList isLoading={isLoading} data={data} />
      </section>
    </>
  );
};

export default Home;

Home.additionalInfo = {
  getLayout: (page) => (
    <SidebarLayout pageTitle="My Tickets" backBtn={false}>
      {page}
    </SidebarLayout>
  ),
  requiresAuth: true,
};
