import Head from "next/head";
import { SidebarLayout } from "~/components/layout";
import { MovieCategorySection } from "~/components/ui";
import { type NextPageWithLayout } from "../../_app";

const TopMoviesPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>MovieMania 🎬 - Top Movies</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <MovieCategorySection title={"Top Movies"} category={"Top Movies"} />
      </>
    </>
  );
};

export default TopMoviesPage;

TopMoviesPage.additionalInfo = {
  getLayout: (page) => (
    <SidebarLayout pageTitle="Choose a movie" backBtn={false}>
      {page}
    </SidebarLayout>
  ),
  requiresAuth: false,
};
