import Head from "next/head";
import { useRouter } from "next/router";
import { SidebarLayout } from "~/components/layout";
import { Heading } from "~/components/typography";
import { type NextPageWithLayout } from "../../../_app";

const ReservationPage: NextPageWithLayout = ({}) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>MovieMania 🎬 - Reservation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Heading tag={"h1"}>Reservation page</Heading>
      </>
    </>
  );
};

export default ReservationPage;

ReservationPage.additionalInfo = {
  getLayout: (page) => (
    <SidebarLayout backBtn={true} pageTitle="Choose seats">
      {page}
    </SidebarLayout>
  ),
  requiresAuth: true,
};
