import { type Ticket } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { useMemo, useState } from "react";
import { FormProvider, useForm, type SubmitHandler } from "react-hook-form";
import { toast } from "react-hot-toast";
import { SeatIcon } from "~/components/icons";
import { SidebarLayout } from "~/components/layout";
import { Small } from "~/components/typography";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  Button,
  Screen,
} from "~/components/ui";
import { api } from "~/utils/api";
import { handleTRPCErrors } from "~/utils/errors";
import { type NextPageWithLayout } from "../../../_app";

const ReservationPage: NextPageWithLayout = ({}) => {
  const router = useRouter();

  const methods = useForm<{
    seats: string[];
  }>();

  const showId = router.query.id as string;

  const [selectedTickets, setSelectedTickets] = useState<Ticket[] | null>(null);
  const [showAlert, setShowAlert] = useState<boolean>(false);

  const { data, isLoading } = api.shows.getOneById.useQuery(
    {
      showId,
    },
    {
      onError: (error) => {
        const { isNotFound } = handleTRPCErrors({
          message: error.data?.stack,
          code: error.data?.code,
        });
        if (isNotFound) {
          void router.push("/not-found");
        }
      },
    }
  );

  const allTickets = useMemo(() => {
    if (data) {
      return data.show.tickets;
    }
  }, [data]);

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    console.log("change", event.target.value);
    const ticketId = event.target.value;
    const ticketSelected = event.target.checked;

    if (ticketSelected === true) {
      if (allTickets) {
        if (selectedTickets) {
          setSelectedTickets([
            ...selectedTickets,
            ...allTickets.filter((ticket) => ticketId === ticket.id),
          ]);
        } else {
          setSelectedTickets(
            allTickets.filter((ticket) => ticketId === ticket.id)
          );
        }
      }
    } else {
      if (selectedTickets) {
        setSelectedTickets(
          selectedTickets.filter((ticket) => ticketId !== ticket.id)
        );
      }
    }
  };

  const onSubmit: SubmitHandler<{ seats: string[] }> = ({ seats }) => {
    if (allTickets && seats && seats.length > 0 && selectedTickets) {
      setShowAlert(true);
    } else {
      toast.error("Select at least one available seat first");
    }
  };

  return (
    <>
      <Head>
        <title>MovieMania 🎬 - Reservation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="mt-6">
          <Screen />
        </div>
        {isLoading ? (
          <>Loading</>
        ) : (
          <>
            <FormProvider {...methods}>
              <form onSubmit={methods.handleSubmit(onSubmit)}>
                <div className="mx-auto my-14 grid max-w-3xl grid-cols-6 gap-3 sm:grid-cols-6 md:grid-cols-6">
                  {allTickets &&
                    allTickets.map((ticket, index) => (
                      <div key={index}>
                        <input
                          id={`seat-${ticket.id}`}
                          value={ticket.id}
                          type="checkbox"
                          className="peer hidden"
                          defaultChecked={!ticket.isAvailable}
                          disabled={!ticket.isAvailable}
                          {...methods.register("seats", { onChange: onChange })}
                        />
                        <label
                          htmlFor={`seat-${ticket.id}`}
                          className={`inline-flex h-auto cursor-pointer items-center justify-between rounded-full p-2 `}
                        >
                          <SeatIcon
                            width="3"
                            height="3"
                            className={`${
                              ticket.isAvailable
                                ? selectedTickets &&
                                  selectedTickets.find(
                                    (ticketSelected) =>
                                      ticketSelected.id === ticket.id
                                  )
                                  ? "fill-accent"
                                  : "fill-white"
                                : "fill-red-500"
                            }`}
                          />
                        </label>
                      </div>
                    ))}
                </div>
                <div className="flex justify-center">
                  <Button className="w-80 py-4">Confirm Selection</Button>
                </div>
              </form>
            </FormProvider>
            <div className="mt-14 flex justify-center">
              <div className="flex gap-5">
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-white"></div>
                  <Small className="font-normal">Available</Small>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-red-500"></div>
                  <Small className="font-normal">Reserved</Small>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-accent"></div>
                  <Small className="font-normal">Selected</Small>
                </div>
              </div>
            </div>
          </>
        )}
      </section>
      <AlertDialog open={showAlert} onOpenChange={() => setShowAlert(false)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="mb-5">
              Sign in with a provider
            </AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="flex flex-col gap-4">Hello</div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter className="mt-4">
            <AlertDialogCancel className="border-none bg-red-500 text-white outline-none focus:outline-none hover:bg-red-600">
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction className="rounded-full border-none bg-primary text-white outline-none focus:outline-none hover:bg-primary">
              Buy Tickets
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};

export default ReservationPage;

ReservationPage.additionalInfo = {
  getLayout: (page) => (
    <SidebarLayout backBtn={true} pageTitle="Choose seats">
      {page}
    </SidebarLayout>
  ),
  requiresAuth: true,
};
