import Head from "next/head";
import { useRouter } from "next/router";
import { SidebarLayout } from "~/components/layout";
import { Heading, Paragraph } from "~/components/typography";
import { api } from "~/utils/api";
import { type NextPageWithLayout } from "../_app";

const SingleMoviePage: NextPageWithLayout = () => {
  const router = useRouter();
  const { slug } = router.query;
  const { isLoading, data } = api.movies.getByName.useQuery({
    movieName: slug as string,
  });

  console.log(data);

  return (
    <>
      <Head>
        <title>MovieMania 🎬 - Upcoming</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Heading tag="h1" variant={"h1"}>
          Single Movie Page
        </Heading>
        <Paragraph>{data?.movie?.title}</Paragraph>
      </>
    </>
  );
};

export default SingleMoviePage;

SingleMoviePage.additionalInfo = {
  getLayout: (page) => <SidebarLayout backBtn={true}>{page}</SidebarLayout>,
  requiresAuth: false,
};
