import Head from "next/head";
import { SidebarLayout } from "~/components/layout";
import { MovieCategorySection } from "~/components/ui";
import { type NextPageWithLayout } from "../../_app";

const NowPlayingPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>MovieMania 🎬 - Now Playing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <MovieCategorySection title={"Now Playing"} category={"Now Playing"} />
      </>
    </>
  );
};

export default NowPlayingPage;

NowPlayingPage.additionalInfo = {
  getLayout: (page) => (
    <SidebarLayout pageTitle="Choose a movie" backBtn={false}>
      {page}
    </SidebarLayout>
  ),
  requiresAuth: false,
};
